repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace

- repo: https://github.com/yzaimoglu/pre-commit-golang
  rev: f2040ec9cf05861e7accdd5081986ef26c83cae8
  hooks:
    - id: golangci-lint
    - id: go-mod-tidy
