version: '3.5'

services:
  mongodb:
    image: mongo:latest
    env_file: backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - backend_net
    volumes:
      - mongodb:/data/db

networks:
  backend_net:
    driver: bridge

volumes:
    mongodb:
