# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o flathunter-server ./cmd/server

# Run stage
FROM alpine
WORKDIR /app
COPY --from=builder /app/flathunter-server .

CMD [ "/app/flathunter-server" ]