version: '3.7'

services:
  arangodb:
    image: arangodb:latest
    env_file: backend/.env
    environment:
      ARANGO_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

networks:
  backend_net:
    driver: bridge

volumes:
    mongodb:
    arangodb_data_container:
    arangodb_apps_data_container:
