# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o flathunter-client ./cmd/client

# Run stage
FROM alpine
WORKDIR /app
COPY --from=builder /app/flathunter-client .

CMD [ "/app/flathunter-client" ]
