# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN cd backend && go build -o ../flathunter-server ./cmd/server

# Run stage
FROM alpine

WORKDIR /app
COPY --from=builder /app/flathunter-server .

RUN apk add dumb-init
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD [ "/app/flathunter-server" ]
