swagger: '2.0'
info:
  title: Flathunter
  version: v0.0.1
host: github.com/yzaimoglu/flathunter
schemes:
  - http
basePath: /api/v1
paths:
  /listings/get:
    get:
      summary: Listings Get
      description: ''
      operationId: 31bbc3eb-e3c7-4df4-909b-0463d3d5c8ea
      parameters:
        - type: string
          default: '1'
          name: page
          required: false
          in: query
      responses:
        default:
          description: no response description was provided for this operation
  /listings/get/102415:
    get:
      summary: Listing Get
      description: ''
      operationId: be8f07f7-9818-468b-a3e7-85fa42f38bef
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user_listings/get/89998:
    get:
      summary: User Listings Get
      description: ''
      operationId: d3330aba-9a56-4fe4-b9f0-a6efa7902d8c
      parameters:
        - type: string
          default: '1'
          name: page
          required: false
          in: query
      responses:
        default:
          description: no response description was provided for this operation
  /user_listings/get/89998/105179:
    get:
      summary: User Listing Get
      description: ''
      operationId: b16426c1-ae51-4e2b-8dde-0ef57095dfa7
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user_listings/insert:
    post:
      summary: Insert User Listing
      description: ''
      operationId: 7c97f7f3-b7dd-4f93-b197-c52d10bcfb48
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=YjM3YTA0NWVkZTg4MGZiNTIxYzk4YTJmNzBmY2M5MGNiNTIxOTRiYzU1MzE1ZmJlMTVjMWZkNWU1YmRmZDAzNGUzM2IxYjUyYTBkZGNiNzAwM2MyNDMyODhkMWIxMDZmYjI5MWU5NDFhODM5ZTQ2ZWE2MWM3OWM2MDg0MDNkMThkYzE3YWM4YWU0YWQ2MWZlZjA0ZmM2ZTk3YTFlMTQ3ZGMzODJjZDJmYThlZmQ2ODJlMmY2Y2M4MWU0OTZiZDlhMzJiYjNiYzA1MjMzNTVmMWJlYzdkYTlhNzk4MjJiMzNlYjU1ZTk4ODU4MDVkNzdhMzkzOWYyODNiNTgzMTY4Nw==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{"user":"89998","listing":"102415","notified":false}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /user_listings/delete/102515:
    delete:
      summary: Delete User Listing
      description: ''
      operationId: f13debf4-f6ab-4ceb-8218-706465a18a34
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=YjM3YTA0NWVkZTg4MGZiNTIxYzk4YTJmNzBmY2M5MGNiNTIxOTRiYzU1MzE1ZmJlMTVjMWZkNWU1YmRmZDAzNGUzM2IxYjUyYTBkZGNiNzAwM2MyNDMyODhkMWIxMDZmYjI5MWU5NDFhODM5ZTQ2ZWE2MWM3OWM2MDg0MDNkMThkYzE3YWM4YWU0YWQ2MWZlZjA0ZmM2ZTk3YTFlMTQ3ZGMzODJjZDJmYThlZmQ2ODJlMmY2Y2M4MWU0OTZiZDlhMzJiYjNiYzA1MjMzNTVmMWJlYzdkYTlhNzk4MjJiMzNlYjU1ZTk4ODU4MDVkNzdhMzkzOWYyODNiNTgzMTY4Nw==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{"user":"89998","url":"85246"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /users/get:
    get:
      summary: Users Get
      description: ''
      operationId: 4890e738-33ae-4b64-95a4-fc6b19df187c
      parameters:
        - type: string
          default: '1'
          name: page
          required: false
          in: query
      responses:
        default:
          description: no response description was provided for this operation
  /user/get_id/89998:
    get:
      summary: User Get By Id
      description: ''
      operationId: 5338cee4-6343-477e-917e-e9a98a6248b6
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user/get_email/yagizalp@zaimoglu.de:
    get:
      summary: User Get By Email
      description: ''
      operationId: c046fa74-4199-4d82-9709-a7862f655165
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user/change_password:
    put:
      summary: User Get By Email
      description: ''
      operationId: 8b19ea7a-4f88-4a4e-8b28-3bbbc32f9acf
      consumes:
        - application/json
      parameters:
        - required: false
          schema:
            type: string
            default: '{"user":"89998","old_password":"old_password","new_password":"password"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /crawler/urls/get:
    get:
      summary: URLS Get
      description: ''
      operationId: ea132596-89ef-43e3-84a5-57a881f5bfa0
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user_urls/get/89998:
    get:
      summary: User URLs Get
      description: ''
      operationId: 1e967037-4e6b-4990-85f5-9d38df709b9d
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user_urls/get/89998/98942:
    get:
      summary: User URL Get
      description: ''
      operationId: 38871399-4537-4379-8711-ec3b007843f0
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /urls/get/48155:
    get:
      summary: URL Get
      description: ''
      operationId: baa35b8d-da91-47a0-ab75-d25dae88fabb
      responses:
        default:
          description: no response description was provided for this operation
      parameters: []
  /user_urls/insert:
    post:
      summary: Insert User URL
      description: ''
      operationId: 98813a3d-fe07-4a30-85f8-5710944e8e2c
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=YjM3YTA0NWVkZTg4MGZiNTIxYzk4YTJmNzBmY2M5MGNiNTIxOTRiYzU1MzE1ZmJlMTVjMWZkNWU1YmRmZDAzNGUzM2IxYjUyYTBkZGNiNzAwM2MyNDMyODhkMWIxMDZmYjI5MWU5NDFhODM5ZTQ2ZWE2MWM3OWM2MDg0MDNkMThkYzE3YWM4YWU0YWQ2MWZlZjA0ZmM2ZTk3YTFlMTQ3ZGMzODJjZDJmYThlZmQ2ODJlMmY2Y2M4MWU0OTZiZDlhMzJiYjNiYzA1MjMzNTVmMWJlYzdkYTlhNzk4MjJiMzNlYjU1ZTk4ODU4MDVkNzdhMzkzOWYyODNiNTgzMTY4Nw==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{"user":"89998","url":"https://www.ebay-kleinanzeigen.de/s-berlin/mietwohnung/k0l3331","platform":"ebay_kleinanzeigen"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /user_urls/delete/94390:
    delete:
      summary: Delete User URL
      description: ''
      operationId: 2e886f6c-a60b-4302-aa2d-98aad22f00a9
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=YjM3YTA0NWVkZTg4MGZiNTIxYzk4YTJmNzBmY2M5MGNiNTIxOTRiYzU1MzE1ZmJlMTVjMWZkNWU1YmRmZDAzNGUzM2IxYjUyYTBkZGNiNzAwM2MyNDMyODhkMWIxMDZmYjI5MWU5NDFhODM5ZTQ2ZWE2MWM3OWM2MDg0MDNkMThkYzE3YWM4YWU0YWQ2MWZlZjA0ZmM2ZTk3YTFlMTQ3ZGMzODJjZDJmYThlZmQ2ODJlMmY2Y2M4MWU0OTZiZDlhMzJiYjNiYzA1MjMzNTVmMWJlYzdkYTlhNzk4MjJiMzNlYjU1ZTk4ODU4MDVkNzdhMzkzOWYyODNiNTgzMTY4Nw==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{"user":"89998","url":"85246"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /auth/register:
    post:
      summary: Register
      description: ''
      operationId: 54467884-1bfa-4070-b638-be3676b0aecb
      consumes:
        - application/json
      parameters:
        - required: false
          schema:
            type: string
            default: '{"email":"yagizalp@zaimoglu.de","password":"password","password_repeat":"password"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /auth/login:
    post:
      summary: Login
      description: ''
      operationId: 7087c251-8409-4b56-a899-8bd548f5f455
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=Y2RjOWU4ZDQ3ODUwNWZhMWYyYWQ5NzJmNTJlZDZlOWQzM2YxMDBhYzk5ZmUyYjk2NDZiZWQwMDBmYTIxOTU0MGYyMzlmYTFhNmI2MTMxY2IwMWI5NWQ4Yzc0OWJmNmYzYmFhOGIwZTEzNGI5ZTY2M2MxYzI3N2ViYmEzMDM0NWQ0ZWNhNzJlZjk1ZjBhODExM2Q0ODg3YzRiYTlkNDAwOTY4MWY1ZjczZjA5MjRiNGU2ZjJmYjQ5NDE2ODFkMzE0ODRkYzAyOTk2OTM2NDk5NGU2MDE5MWY0NDViZmZjYTFlMmYxZjYwYThmZWU4NWZlOWJlZDliMzY5OTM0NDVkZA==
          name: Cookie
          required: false
          in: query
        - required: false
          schema:
            type: string
            default: '{"email":"yagizalp@zaimoglu.de","password":"password"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /auth/logout:
    delete:
      summary: Logout
      description: ''
      operationId: 98ec2a1d-d92b-4ca5-b02f-55b876e0911e
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=OWZmNzNlZmNjNDNjMWVjMzFhYzU1ODM5YjQyZjcyMzBhMWM0YzE2YTU1NjM4OTE0NWI1NThlOTY0YzA2MmE4MDAyNGI2N2FmZWI2OTBmY2JhNmI3OTM0ZWRmZDQyZDQ5ZjhhYjdmM2I3NDI0YmI0NmEwMjQ0MTMwMWFmMmYzYzk5ZDU1ZDQ4ZWM5NDMzM2JhYzY5MDY5ZGRiOTliMDZmNDI2NGMyOTdlMDZkZGJiMTE5MWRmYzA0Yjg2MmQ1NzBmMzFjNGJjZWFkNDkxMGIyMzQ4ODg1NTI0M2NiOTRkMzA3MjQ1NjQ3N2JjYTBjMTY5Y2UyN2FhNjE4ZTY2YmZjOQ==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
  /auth/session:
    get:
      summary: Session Check
      description: ''
      operationId: 69c53771-0421-4279-a4ba-a3736f57ebfb
      consumes:
        - application/json
      parameters:
        - type: string
          default: session_token=YjM3YTA0NWVkZTg4MGZiNTIxYzk4YTJmNzBmY2M5MGNiNTIxOTRiYzU1MzE1ZmJlMTVjMWZkNWU1YmRmZDAzNGUzM2IxYjUyYTBkZGNiNzAwM2MyNDMyODhkMWIxMDZmYjI5MWU5NDFhODM5ZTQ2ZWE2MWM3OWM2MDg0MDNkMThkYzE3YWM4YWU0YWQ2MWZlZjA0ZmM2ZTk3YTFlMTQ3ZGMzODJjZDJmYThlZmQ2ODJlMmY2Y2M4MWU0OTZiZDlhMzJiYjNiYzA1MjMzNTVmMWJlYzdkYTlhNzk4MjJiMzNlYjU1ZTk4ODU4MDVkNzdhMzkzOWYyODNiNTgzMTY4Nw==
          name: Cookie
          required: false
          in: header
        - required: false
          schema:
            type: string
            default: '{"email":"yagizalp@zaimoglu.de","password":"password"}'
          in: body
          name: body
      responses:
        default:
          description: no response description was provided for this operation
tags: []
